{% set name = "duckdb" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/duckdb-{{ version }}.tar.gz
  sha256: 3a52c975cc13b965580cd00af1538b2d9f6b896431f97121dbee7ce715edcd2a

build:
  number: 0
  skip: true  # [not linux]
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools-scm <7.0.0
    - pybind11 >=2.6.0
    - pip
  run:
    - python

test:
  imports:
    # Throws syntax error for "import duckdb-stub"
    #- duckdb-stubs
    - duckdb
    - duckdb_query_graph
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.duckdb.org
  summary: DuckDB embedded database
  license: MIT
  license_file: LICENSE
  description: |
    DuckDB is an in-process SQL OLAP database management system.

    PyPI: [https://pypi.org/project/duckdb/](https://pypi.org/project/duckdb/)

    ---

    :fire: The conda-forge recipe was generated with [Conda-Forger App](https://sugatoray-conda-forger.streamlit.app/).

    :point_right: [![Streamlit App](https://static.streamlit.io/badges/streamlit_badge_black_white.svg)](https://sugatoray-conda-forger.streamlit.app/)

    [_streamlit-conda-forger-app]: https://sugatoray-conda-forger.streamlit.app/

  dev_url: https://github.com/duckdb/duckdb/blob/master/tools/pythonpkg
  doc_url: https://duckdb.org/docs/api/python/overview

extra:
  recipe-maintainers:
    - sugatoray
